- name: Install required packages
  apt:
    name:
      - python3
      - python3-pip
      - python3-pytest
      - python3-requests
    state: present
  become: true

- name: Copy integration test scripts
  copy:
    src: files/
    dest: /opt/crowdin/tests/
  become: true

- name: Run integration tests
  command: pytest /opt/crowdin/tests/
  register: test_result
  become: true

- name: Display test results
  debug:
    var: test_result.stdout_lines