---
- name: Install MySQL package
  apt:
    name: mysql-server
    state: present
  become: true

- name: Start MySQL service
  service:
    name: mysql
    state: started
    enabled: true
  become: true

- name: Create MySQL configuration file
  template:
    src: my.cnf.j2
    dest: /etc/mysql/my.cnf
  notify: Restart MySQL
  become: true

- name: Create example database
  mysql_db:
    name: example_db
    state: present
  become: true

- name: Create example user
  mysql_user:
    name: example_user
    password: example_password
    priv: 'example_db.*:ALL'
    state: present
  become: true