- name: Install UFW
  apt:
    name: ufw
    state: present
  become: true

- name: Allow SSH
  ufw:
    rule: allow
    port: 22
  become: true

- name: Allow HTTP
  ufw:
    rule: allow
    port: 80
  become: true

- name: Allow HTTPS
  ufw:
    rule: allow
    port: 443
  become: true

- name: Enable UFW
  ufw:
    state: enabled
    default: deny
  become: true